// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"sync"

	"github.com/Peripli/service-manager-cli/pkg/auth"
)

type FakeAuthenticationStrategy struct {
	AuthenticateStub        func(user, password string) (*auth.Token, error)
	authenticateMutex       sync.RWMutex
	authenticateArgsForCall []struct {
		user     string
		password string
	}
	authenticateReturns struct {
		result1 *auth.Token
		result2 error
	}
	authenticateReturnsOnCall map[int]struct {
		result1 *auth.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthenticationStrategy) Authenticate(user string, password string) (*auth.Token, error) {
	fake.authenticateMutex.Lock()
	ret, specificReturn := fake.authenticateReturnsOnCall[len(fake.authenticateArgsForCall)]
	fake.authenticateArgsForCall = append(fake.authenticateArgsForCall, struct {
		user     string
		password string
	}{user, password})
	fake.recordInvocation("Authenticate", []interface{}{user, password})
	fake.authenticateMutex.Unlock()
	if fake.AuthenticateStub != nil {
		return fake.AuthenticateStub(user, password)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.authenticateReturns.result1, fake.authenticateReturns.result2
}

func (fake *FakeAuthenticationStrategy) AuthenticateCallCount() int {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return len(fake.authenticateArgsForCall)
}

func (fake *FakeAuthenticationStrategy) AuthenticateArgsForCall(i int) (string, string) {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return fake.authenticateArgsForCall[i].user, fake.authenticateArgsForCall[i].password
}

func (fake *FakeAuthenticationStrategy) AuthenticateReturns(result1 *auth.Token, result2 error) {
	fake.AuthenticateStub = nil
	fake.authenticateReturns = struct {
		result1 *auth.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticationStrategy) AuthenticateReturnsOnCall(i int, result1 *auth.Token, result2 error) {
	fake.AuthenticateStub = nil
	if fake.authenticateReturnsOnCall == nil {
		fake.authenticateReturnsOnCall = make(map[int]struct {
			result1 *auth.Token
			result2 error
		})
	}
	fake.authenticateReturnsOnCall[i] = struct {
		result1 *auth.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticationStrategy) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthenticationStrategy) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.AuthenticationStrategy = new(FakeAuthenticationStrategy)
